name: Arduino CI

on: [push, pull_request]

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Run Arduino Lint
        uses: arduino/arduino-lint-action@v2
        with:
          library-manager: update
          compliance: permissive
          path: ./code/servo_control.ino

      - name: Install Arduino CLI
        uses: arduino/setup-arduino-cli@v2
  
      - name: Arduino Compile      
        uses: arduino/compile-sketches@v1
        with:
          fqbn: "arduino:avr:uno"
